### ISSUE TITLE
Very slow zkey read and witness computation

### ISSUE THREAD

**Issue by fgimenez** [arkworks-rs/circom-compat#46]
Hi, I'm trying to load a zkey and witness files generated with snarkjs following the example at https://github.com/arkworks-rs/circom-compat/blob/master/src/zkey.rs#L875 but it is taking a lot of time, for a circuit with 2920 constraints calculating the witness takes 69.65s, while snarkjs only takes 323ms. Loading the zkey file is ~16s more.

My goal is to generate proofs, which actually takes around 700ms. When I execute the equivalent snarkjs command using the same zkey and witness files I get a similar time to generate the proof, but without all the initial delay to generate the witness and to load the zkey file.

This is what my code basically looks like:
```rust
use ark_circom::{read_zkey, WitnessCalculator};
use log::info;
use std::{fs::File, time::Instant};

fn new(circuit_wasm_path: &str, circuit_zkey_path: &str) -> {
    let mut file = File::open(circuit_zkey_path)?;
    let now = Instant::now();
    let (params, matrices) = read_zkey(&mut file).unwrap();
    info!("reading zkey took {:?}", now.elapsed());

    let now = Instant::now();
    let witness = WitnessCalculator::new(circuit_wasm_path).unwrap();
    info!("generating witness took {:?}", now.elapsed());
}
```
`ark_circom` from current tip of master and default features. I can also share the circuit if needed.

So, is this behaviour expected, am I doing anything wrong?

**Comment by Pratyush** [comment]
Hm that's surprising. DO you have a link to the equivalent snarkjs code?

**Comment by Pratyush** [comment]
If you could share the circuit that'd be lovely.

**Comment by fgimenez** [comment]
hey @Pratyush thank you so much for your response! :heart: 

> Hm that's surprising. DO you have a link to the equivalent snarkjs code?

sure, it looks like this:
```
cd "${SCRIPT_PATH}/../circuits/checker_js"
echo "Generating witness..."
time node generate_witness.js checker.wasm ../input.json witness.wtns

cd "${SCRIPT_PATH}/../circuits"
echo "Generating proof..."
time snarkjs groth16 prove checker_0001.zkey checker_js/witness.wtns proof.json public.json

echo "Verifying proof..."
time snarkjs groth16 verify verification_key.json public.json proof.json
```
using snarkjs v0.7.0.

> If you could share the circuit that'd be lovely.

absolutely, it is based on https://github.com/tornadocash/tornado-core/blob/master/circuits/withdraw.circom but removing all the code related to `recipient`, `relayer`, `fee` and `refund`, and using poseidon as the only hashing function, there are two files, checker.circom:
```
pragma circom 2.1.5;

include "./node_modules/circomlib/circuits/poseidon.circom";
include "merkleTree.circom";

template CommitmentHasher() {
    signal input nullifier;
    signal input secret;
    signal output commitment;
    signal output nullifierHash;

    component commitmentHasher = Poseidon(2);
    component nullifierHasher = Poseidon(2);

    commitmentHasher.inputs[0] <== secret;
    commitmentHasher.inputs[1] <== nullifier;

    var zero = 0;
    nullifierHasher.inputs[0] <== nullifier;
    nullifierHasher.inputs[1] <== zero;

    commitment <== commitmentHasher.out;
    nullifierHash <== nullifierHasher.out;
}

template Checker(levels) {
    signal input root;
    signal input nullifierHash;
    signal input nullifier;
    signal input secret;
    signal input pathElements[levels];
    signal input pathIndices[levels];

    component hasher = CommitmentHasher();
    hasher.nullifier <== nullifier;
    hasher.secret <== secret;
    hasher.nullifierHash === nullifierHash;

    component tree = MerkleTreeChecker(levels);
    tree.leaf <== hasher.commitment;
    tree.root <== root;
    for (var i = 0; i < levels; i++) {
        tree.pathElements[i] <== pathElements[i];
        tree.pathIndices[i] <== pathIndices[i];
    }
}

component main {public [root, nullifierHash]} = Checker(10);
```
and merkleTree.circom:
```
pragma circom 2.1.5;

include "./node_modules/circomlib/circuits/poseidon.circom";

template HashLeftRight() {
    signal input left;
    signal input right;
    signal output hash;

    component hasher = Poseidon(2);
    hasher.inputs[0] <== left;
    hasher.inputs[1] <== right;
    hash <== hasher.out;
}

template DualMux() {
    signal input in[2];
    signal input s;
    signal output out[2];

    s * (1 - s) === 0;
    out[0] <== (in[1] - in[0])*s + in[0];
    out[1] <== (in[0] - in[1])*s + in[1];
}

template MerkleTreeChecker(levels) {
    signal input leaf;
    signal input root;
    signal input pathElements[levels];
    signal input pathIndices[levels];

    component selectors[levels];
    component hashers[levels];

    for (var i = 0; i < levels; i++) {
        selectors[i] = DualMux();
        selectors[i].in[0] <== i == 0 ? leaf : hashers[i - 1].hash;
        selectors[i].in[1] <== pathElements[i];
        selectors[i].s <== pathIndices[i];

        hashers[i] = HashLeftRight();
        hashers[i].left <== selectors[i].out[0];
        hashers[i].right <== selectors[i].out[1];
    }

    root === hashers[levels - 1].hash;
}
```

**Comment by fgimenez** [comment]
@Pratyush please let me know if anything else is needed. I'd love to work on a fix if needed, but would need some guidance.

**Comment by fgimenez** [comment]
Just setting `opt-level = 3` for the test profile is enough for the witness calculation to take a reasonable amount of time in the tests, closing.

**Comment by botdad** [comment]
If anyone else comes across this because of slow zkey reading the culprit is `G1Affine::new` instead of `G1Affine::new_unchecked`. I didn't need the extra checks for my use case and switching to _unchecked sped it up from 17s to under 100ms

https://github.com/arkworks-rs/circom-compat/blob/170b10fc9ed182b5f72ecf379033dda023d0bf07/src/zkey.rs#L347-L358

**Comment by gldeng** [comment]
Hi @botdad , I'm a bit new to rust. Can you share how you made the workaround?

**Comment by botdad** [comment]
@gldeng Yeah, you can see the changes on our branch here: https://github.com/rally-dfs/circom-compat/commit/1b402261d4bd7dc566e7ff671fea728f2735957f

You can also use the branch directly which already has this change. https://github.com/rally-dfs/circom-compat
